1. Python program to add two Matrices

In [17]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(X)):  
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


2. Python program to multiply two matrices

In [18]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]
            
            
for r in result:
    print(r)

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


3. Python program for Matrix Product

4. Adding and Subtracting Matrices in Python

In [20]:
import numpy as np

X = np.array([[1,2],[3,4]])
Y = np.array([[4,5],[6,7]])

#subtraction of two matrix

print(np.subtract(X,Y))

#Addition of two matrix

print(np.add(X,Y))


[[-3 -3]
 [-3 -3]]
[[ 5  7]
 [ 9 11]]


5. Transpose a matrix in Single line in Python

In [26]:
X = ([[1,2,3],[4 ,5,6],[7 ,8,9]])

import numpy as np
np.transpose(X)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

6. Python | Matrix creation of n*n

In [45]:
N = int(input())
A = []

for i in range(N):
    A.append((list(range(1 + N * i, 1 + N * (i + 1)))))
A

6


[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30],
 [31, 32, 33, 34, 35, 36]]

7. Python | Get Kth Column of Matrix

In [51]:
def kth_in_matrix(matrix,k_th):
    
    L = []

    for i in matrix:
        L.append(i[k_th])
    return L

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

kth_in_matrix(X,1)


[2, 5, 8]

8. Python – Vertical Concatenation in Matrix

In [11]:
def V_C(matrix):
    
    L = []
    for j in range(len(matrix[0])):
            for i in matrix:
                L.append(i[j])
    print(L)

                
X = [['Am','It'],
    ['I','Right'],
    ['Doing','Way']]

V_C(X)

['Am', 'I', 'Doing', 'It', 'Right', 'Way']


9. Python program to check if a string is palindrome or not

In [2]:
def palindrome_check(string):
    
    if string==string[::-1]:
        print(' cought you')
    else :
        print(' wrong guess ')
        
q = "tenet"
a = "asad"
palindrome_check(q)
palindrome_check(a)

 cought you
 wrong guess 


10. Python program to check whether the string is Symmetrical or Palindrome

In [3]:
def symmertical_or_palindrome(string):
    
    half = int(len(string) / 2)
    
    
    if string == string[::-1]:
        print(string, ' is palindrome')
        
    else :
        print('no-palindrone')

    
    if len(string) % 2 == 0 :
        first_str = string[:half]
        sec_str = string[half:]
    
        if first_str == sec_str :
            print(string, 'is symmertrical')
        
        else :
            print('no-symmertrical')
    

A = 'tenet'
B = "aamaam"

symmertical_or_palindrome(A)
symmertical_or_palindrome(B)

tenet  is palindrome
no-palindrone
aamaam is symmertrical
